### ISSUE TITLE
Feature request: Multiple windings Transformer

### ISSUE THREAD

**Issue by suryatejasharma** [sharpie7/circuitjs1#278] opened 2018-11-13 19:14 UTC
We have a normal transformer and a tapped transformer in flastad, it would be great if you could add a transformer with two or more primary windings (with possibility of changing polarities to simulate blocking oscillators) and potentially two or more secondary windings would be great. 
![block_ref_2604](https://user-images.githubusercontent.com/45013549/48437088-70c19400-e74e-11e8-96a9-7dd0be8258e7.gif)

**Comment by sharpie7** [comment] 2018-11-13 20:14
Thanks for the suggestion. I am closing the issue as it is a duplicate of #272

**Closed by sharpie7** 2018-11-13 20:14 UTC
