### ISSUE TITLE
Transformers are bugged?

### ISSUE THREAD

**Issue by emilfihlman** [sharpie7/circuitjs1#129] opened 2017-06-16 20:44 UTC
Pictures demonstrate situations that are possible to achieve but which do not reflect reality, unless my understanding of electronics is completely bonkers.

[DC current offset with return to zero, is this an ideal full bridge current rectifier?](https://emil.fi/jako/kuvat/2017-06-16_23-32-18_rkc0p4hY.png)

[DC current offsets with nrz, getting to ac-dc conversion here](https://emil.fi/jako/kuvat/2017-06-16_23-33-07_RRY9VyDd.png)

[DC current with no apparent AC component(s), transformers confirmed for ac-dc converters](https://emil.fi/jako/kuvat/2017-06-16_23-35-29_UvYYsBpy.png)

**Comment by pfalstad** [comment] 2017-06-16 20:51
Yes, see here: http://www.falstad.com/circuit/e-transformerdc.html

For a more realistic transformer, use a smaller inductance, a smaller coupling coefficient, and/or more resistance.

**Comment by emilfihlman** [comment] 2017-06-16 20:53
Is there a patch planned?

**Comment by pfalstad** [comment] 2017-06-16 20:56
What do you want patched?  The simulator uses ideal components in general.  If you want less-ideal components, you have what you need to create them.

**Comment by emilfihlman** [comment] 2017-06-16 20:59
>Transformers are bugged?
>Yes

Ideal transformers shouldn't act as pictures demonstrate. In general, not zeroing the currents on reset causes loads of issues with the simulator.

**Comment by pfalstad** [comment] 2017-06-16 21:08
how should it work?  perhaps you can try it out in spice or some other simulator and gather some data about what should be happening instead.

**Comment by pfalstad** [comment] 2019-03-06 00:21
Hard to say, since the images are missing, but I think this was fixed by #162 .  Either that or it is not a bug.

**Comment by sharpie7** [comment] 2019-03-06 16:40
Believe fixed.

**Closed by sharpie7** 2019-03-06 16:40 UTC

**Comment by emilfihlman** [comment] 2019-03-06 17:24
Images restored
